[package]
name = "raytracer"
version = "0.1.0"
authors = ["xcastilla"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.5"
structopt = { version = "0.3", default-features = false }
